#!/bin/bash
set -e
BASE="https://afth.asso.fr"
IMG="assets/images"
PDF="assets/pdfs"
mkdir -p "$IMG" "$PDF"

echo "=== Images ==="
curl -fL -o "$IMG/logo.gif"       "$BASE/images/logo.gif"       || echo "⚠ logo.gif"
curl -fL -o "$IMG/logo_cneth.png" "$BASE/images/logo_cneth.png" || echo "⚠ logo_cneth"
curl -fL -o "$IMG/afreth.gif"     "$BASE/images/afreth.gif"     || echo "⚠ afreth"
curl -fL -o "$IMG/p-assoc3.png"   "$BASE/images/p-assoc3.png"   || echo "⚠ p-assoc3"
curl -fL -o "$IMG/p-congres.png"  "$BASE/images/p-congres.png"  || echo "⚠ p-congres"
curl -fL -o "$IMG/p-prix.png"     "$BASE/images/p-prix.png"     || echo "⚠ p-prix"
curl -fL -o "$IMG/p-archive.png"  "$BASE/images/p-archive.png"  || echo "⚠ p-archive"
curl -fL -o "$IMG/beraud.jpg"     "$BASE/images/beraud.jpg"      || echo "⚠ beraud"
curl -fL -o "$IMG/carre-nav2.jpg" "$BASE/images/carre-nav2.jpg" || echo "⚠ carre-nav2"

echo "=== PDFs bulletins ==="
curl -fL -o "$PDF/bulletin-2004.pdf" "$BASE/pdfs/bulletin-2004.PDF" || echo "⚠ 2004"
curl -fL -o "$PDF/bulletin-2005.pdf" "$BASE/pdfs/bulletin-2005.pdf" || echo "⚠ 2005"
curl -fL -o "$PDF/bulletin-2006.pdf" "$BASE/pdfs/bulletin-2006.pdf" || echo "⚠ 2006"
curl -fL -o "$PDF/bulletin-2007.pdf" "$BASE/pdfs/bulletin-2007.pdf" || echo "⚠ 2007"
curl -fL -o "$PDF/bulletin-2008.pdf" "$BASE/pdfs/bulletin-2008.pdf" || echo "⚠ 2008"
curl -fL -o "$PDF/bulletin-2009.pdf" "$BASE/pdfs/bulletin-2009.pdf" || echo "⚠ 2009"
curl -fL -o "$PDF/bulletin-2010.pdf" "$BASE/pdfs/bulletin-2010.pdf" || echo "⚠ 2010"
curl -fL -o "$PDF/bulletin-2011.pdf" "$BASE/pdfs/bulletin-2011.pdf" || echo "⚠ 2011"
curl -fL -o "$PDF/bulletin-2012.pdf" "$BASE/pdfs/bulletin-2012.pdf" || echo "⚠ 2012"
curl -fL -o "$PDF/bulletin-2013.pdf" "$BASE/pdfs/bulletin-2013.pdf" || echo "⚠ 2013"
curl -fL -o "$PDF/bulletin-2014.pdf" "$BASE/pdfs/bulletin-2014.pdf" || echo "⚠ 2014"
curl -fL -o "$PDF/bulletin-2015.pdf" "$BASE/pdfs/bulletin-2015.pdf" || echo "⚠ 2015"
curl -fL -o "$PDF/bulletin-2016.pdf" "$BASE/pdfs/bulletin-2016.pdf" || echo "⚠ 2016"
curl -fL -o "$PDF/bulletin-2017.pdf" "$BASE/pdfs/bulletin-2017.pdf" || echo "⚠ 2017"
curl -fL -o "$PDF/bulletin-2018.pdf" "$BASE/pdfs/bulletin-2018.pdf" || echo "⚠ 2018"
curl -fL -o "$PDF/bulletin-2019.pdf" "$BASE/pdfs/bulletin-2019.pdf" || echo "⚠ 2019"
curl -fL -o "$PDF/bulletin-2020.pdf" "$BASE/pdfs/bulletin-2020.pdf" || echo "⚠ 2020"
curl -fL -o "$PDF/bulletin-2021.pdf" "$BASE/pdfs/bulletin-2022.pdf" || echo "⚠ 2021"
curl -fL -o "$PDF/bulletin-2022.pdf" "$BASE/pdfs/bulletin2022.pdf"  || echo "⚠ 2022"
curl -fL -o "$PDF/bulletin-2023.pdf" "$BASE/pdfs/bulletin_2023.pdf" || echo "⚠ 2023"
curl -fL -o "$PDF/bulletin-2024.pdf" "$BASE/pdfs/bulletin_2024.pdf" || echo "⚠ 2024"
curl -fL -o "$PDF/bulletin-2025.pdf" "$BASE/pdfs/bulletin_2025.pdf" || echo "⚠ 2025"

echo "✅ Assets terminés"
